import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import { Timeline } from "~/components/Timeline";
import { Button } from "~/components/Button";
import { LoggedOutBanner } from "~/components/LoggedOutBanner";

const Home: NextPage = () => {

    const { data: session } = useSession()
  return (
    <>

      <Head>
        <title>Dyd</title>
      
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-primary" >
        <div data-theme='dark' className="w-100 p-10 flex justify-end">
        <Button variant="primary" onClick={signIn}>Sign In</Button>
        <Button variant="primary" onClick={signOut}>Sign Out</Button>
        </div>
        <div>
        <Timeline />
        </div>
        <div className="w-full h-20 bottom-0 absolute left-0 bg-secondary">
        <LoggedOutBanner />
        </div>
      </main>
   
    </>
  );
};

export default Home;


