import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";

import { Timeline } from "~/components/Timeline";
import { Button } from "~/components/Button";

const Home: NextPage = () => {

  return (
    <>

      <Head>
        <title>Dyd</title>
      
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-primary" >
        <div data-theme='dark' className="w-100 p-10 flex justify-end">
        <Button variant="primary" onClick={signIn}>Sign In</Button>
        <Button variant="primary" onClick={signOut}>Sign Out</Button>
        </div>
        <div>
        <Timeline />
        </div>
      </main>
   
    </>
  );
};

export default Home;


